base_config:
  - configs/popcs_ds_beta6.yaml
  - configs/midi/cascade/opencs/opencpop_statis.yaml

binarizer_cls: data_gen.opencpop.OpencpopBinarizer
binary_data_dir: 'data/binary/opencpop-midi-dp'

#switch_midi2f0_step: 174000
use_midi: true  #  for midi exp
use_gt_f0: false  #  for midi exp
use_gt_dur: false  # for further midi exp
lambda_f0: 1.0
use_uv: false
#lambda_uv: 1.0
#lambda_energy: 0.1
lambda_ph_dur: 0.3
lambda_sent_dur: 3.0
lambda_word_dur: 1.0
predictor_grad: 0.1
# pe_enable: true
# pe_ckpt: 'checkpoints/0102_xiaoma_pe'

fs2_ckpt: ''  #
#num_valid_plots: 0
task_cls: src.diffsinger_task.DiffSingerMIDITask

K_step: 100
lr: 0.0004
decay_steps: 125000
max_tokens: 16000
predictor_layers: 5
dilation_cycle_length: 4  # *
rel_pos: true
dur_predictor_layers: 5  # *
max_updates: 500000
gaussian_start: true
pndm_speedup: 1