base_config:
  - configs/popcs_ds_beta6.yaml
  - configs/midi/cascade/opencs/opencpop_statis.yaml

audio_sample_rate: 44100
audio_num_mel_bins: 128
hop_size: 512            # Hop size.
fft_size: 2048           # FFT size.
win_size: 2048           # FFT size.
fmin: 40
fmax: 16000
vocoder: NsfHifiGAN
vocoder_ckpt: checkpoints/nsf_hifigan/model
use_nsf: true

binarization_args:
  with_wav: false
  with_spk_embed: false
  with_align: true
raw_data_dir: 'data/raw/opencpop/segments'
processed_data_dir: 'xxx'
binary_data_dir: 'data/binary/opencpop-midi-dp'
g2p_dictionary: dictionaries/opencpop-strict.txt
binarizer_cls: data_gen.opencpop.OpencpopBinarizer
spec_min: [-5]
spec_max: [0]
keep_bins: 128

num_spk: 1
test_prefixes: [
    '2044',
    '2086',
    '2092',
    '2093',
    '2100',
]

#switch_midi2f0_step: 174000
use_midi: true  #  for midi exp
use_gt_f0: false  #  for midi exp
use_gt_dur: false  # for further midi exp
lambda_f0: 1.0
use_uv: false
#lambda_uv: 1.0
#lambda_energy: 0.1
lambda_ph_dur: 0.3
lambda_sent_dur: 3.0
lambda_word_dur: 1.0
predictor_grad: 0.1
#pe_enable: true
#pe_ckpt: 'checkpoints/0102_xiaoma_pe'
pitch_loss: l2
diff_loss_type: l2

fs2_ckpt: ''  #
#num_valid_plots: 0
task_cls: src.diffsinger_task.DiffSingerMIDITask

K_step: 1000
timesteps: 1000
max_beta: 0.02
lr: 0.0005
decay_steps: 50000
max_tokens: 80000
predictor_layers: 5
dilation_cycle_length: 4  # *
rel_pos: true
dur_predictor_layers: 5  # *
max_updates: 250000
gaussian_start: true
pndm_speedup: 10

#hidden_size: 256
residual_layers: 20
residual_channels: 512
max_sentences: 48
val_check_interval: 2000
